Repository kubernetes-sigs/cluster-proportional-vertical-autoscaler, pull requests merged in 2019-11, with the labels that each got.

#25 Update makefile - modify version extraction
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 update dependencies management instruction in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#29 Update to apps/v1 apiVersion
  README.md
  examples/cpvpa-nginx-example-with-configmap.yaml
  examples/cpvpa-nginx-example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#26 Remove -ti in docker build to allow automation run the build.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#30 Add version to user-agent
  pkg/autoscaler/k8sclient/k8sclient.go
Labels: approved, cncf-cla: yes, lgtm, size/S
