Repository kubernetes-sigs/cluster-proportional-vertical-autoscaler, pull requests merged in 2019-04, with the labels that each got.

#15 Rebase CPVPA to distroless
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#16 Fix typo in OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#13 switch build status to svg
  README.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS
